spring:
  application:
    name: batch
  datasource:
    url: jdbc:h2:mem:testdb;Mode=PostgreSQL
    platform: h2
  jpa:
    hibernate:
      ddl-auto: create
      
server:
  port: 9090
  

#eureka:
#  client:
#    service-url:
#      deault-zone:${EUREKA_ZONE}
        
      

